---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/paypal
  label: Paypal
  create: all
  match: "**/*"
- type: directory
  path: content/impressum
  label: Impressum
  create: all
  match: "**/*"
- type: directory
  path: content/datenschutz
  label: Datenschutz
  create: all
  match: "**/*"
- type: directory
  path: content/bestellung
  label: Bestellung
  create: all
  match: "**/*"
- type: directory
  path: content/bestellen
  label: Bestellen
  create: all
  match: "**/*"
- type: directory
  path: content/agb
  label: Agb
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.80.0
